name: Bundle analyzer

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate bundle analysis
        run: npm run analyze
        env:
          ANALYZE: true

      - name: Upload analysis HTML to artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle-analysis
          path: .next/analyze

      - name: Add bundle analysis summary comment to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const summary = 'Bundle Analysis Summary: [https://eventuras-bundle.pages.dev]'; 
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

  deploy:
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download bundle analysis HTML
        uses: actions/download-artifact@v2
        with:
          name: bundle-analysis
          path: public/analyze

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          project: eventuras-bundle
